// <auto-generated />
using GMonitoria.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GMonitoria.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GMonitoriaContext))]
    [Migration("20180430191947_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("GMonitoria.Domain.Entities.ComponenteCurricular", b =>
                {
                    b.Property<string>("ComponenteCurricularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("COMPONENTE_CURRICULAR_ID")
                        .HasMaxLength(200);

                    b.Property<string>("CursoId")
                        .IsRequired()
                        .HasColumnName("CURSO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("ProfessorId")
                        .IsRequired()
                        .HasColumnName("PROFESSOR_ID")
                        .HasMaxLength(200);

                    b.Property<string>("XcomponenteCurricular")
                        .IsRequired()
                        .HasColumnName("XCOMPONENTE_CURRICULAR")
                        .HasMaxLength(200);

                    b.HasKey("ComponenteCurricularId");

                    b.HasIndex("CursoId")
                        .HasName("FK_COMPONENTE_CURRICULAR_CURSO");

                    b.HasIndex("ProfessorId")
                        .HasName("FK_COMPONENTE_CURRICULAR_PROFESSOR");

                    b.ToTable("componente_curricular");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Curso", b =>
                {
                    b.Property<string>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CURSO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("Xcurso")
                        .IsRequired()
                        .HasColumnName("XCURSO")
                        .HasMaxLength(200);

                    b.HasKey("CursoId");

                    b.ToTable("CURSO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.HorarioAtendimento", b =>
                {
                    b.Property<string>("HorarioAtendimentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("HORARIO_ATENDIMENTO_ID")
                        .HasMaxLength(200);

                    b.Property<int>("DataAlteracao");

                    b.Property<string>("DiaDaSemana")
                        .IsRequired()
                        .HasColumnName("DIA_DA_SEMANA")
                        .HasMaxLength(200);

                    b.Property<DateTime>("HoraFim")
                        .HasColumnName("HORA_FIM")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnName("HORA_INICIO")
                        .HasColumnType("datetime");

                    b.Property<string>("InscricaoId")
                        .IsRequired()
                        .HasColumnName("INSCRICAO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasColumnName("SALA")
                        .HasMaxLength(200);

                    b.HasKey("HorarioAtendimentoId");

                    b.HasIndex("InscricaoId")
                        .HasName("FK_HORARIO_ATENDIMENTO_INSCRICAO");

                    b.ToTable("HORARIO_ATENDIMENTO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Inscricao", b =>
                {
                    b.Property<string>("InscricaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("INSCRICAO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("AlunoId")
                        .IsRequired()
                        .HasColumnName("ALUNO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnName("CPF")
                        .HasMaxLength(200);

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnName("PROTOCOLO")
                        .HasMaxLength(200);

                    b.Property<string>("VagaRequisicaoId")
                        .IsRequired()
                        .HasColumnName("VAGA_REQUISICAO_ID")
                        .HasMaxLength(200);

                    b.HasKey("InscricaoId");

                    b.HasIndex("AlunoId")
                        .HasName("FK_INSCRICAO_ALUNO");

                    b.HasIndex("VagaRequisicaoId")
                        .HasName("FK_INSCRICAO_VAGA_REQUISICAO");

                    b.ToTable("inscricao");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.InscricaoAceitacaoMonitoria", b =>
                {
                    b.Property<string>("InscricaoAceitacaoMonitoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("INSCRICAO_ACEITACAO_MONITORIA_ID")
                        .HasMaxLength(200);

                    b.Property<string>("InscricaoId")
                        .IsRequired()
                        .HasColumnName("INSCRICAO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("VagaId")
                        .IsRequired()
                        .HasColumnName("VAGA_ID")
                        .HasMaxLength(200);

                    b.HasKey("InscricaoAceitacaoMonitoriaId");

                    b.HasIndex("InscricaoId")
                        .HasName("FK_INSCRICAO_ACEITACAO_MONITORIA_INSCRICAO");

                    b.HasIndex("VagaId")
                        .HasName("FK_INSCRICAO_ACEITACAO_MONITORIA_VAGA");

                    b.ToTable("inscricao_aceitacao_monitoria");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.InscricaoProva", b =>
                {
                    b.Property<string>("InscricaoProvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("INSCRICAO_PROVA_ID")
                        .HasMaxLength(200);

                    b.Property<string>("InscricaoId")
                        .IsRequired()
                        .HasColumnName("INSCRICAO_ID")
                        .HasMaxLength(200);

                    b.Property<float>("Nota")
                        .HasColumnName("NOTA");

                    b.Property<string>("ProvaId")
                        .IsRequired()
                        .HasColumnName("PROVA_ID")
                        .HasMaxLength(200);

                    b.HasKey("InscricaoProvaId");

                    b.HasIndex("InscricaoId")
                        .HasName("FK_INSCRICAO_PROVA_INSCRICAO");

                    b.HasIndex("ProvaId")
                        .HasName("FK_INSCRICAO_PROVA_PROVA");

                    b.ToTable("inscricao_prova");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.InscricaoResultado", b =>
                {
                    b.Property<string>("InscricaoResultadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("INSCRICAO_RESULTADO_ID")
                        .HasMaxLength(200);

                    b.Property<int?>("Classificacao")
                        .HasColumnName("CLASSIFICACAO")
                        .HasColumnType("int(11)");

                    b.Property<string>("InscricaoId")
                        .IsRequired()
                        .HasColumnName("INSCRICAO_ID")
                        .HasMaxLength(200);

                    b.HasKey("InscricaoResultadoId");

                    b.HasIndex("InscricaoId")
                        .HasName("FK_INSCRICAO_RESULTADO_INSCRICAO");

                    b.ToTable("inscricao_resultado");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Papel", b =>
                {
                    b.Property<string>("PapelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PAPEL_ID")
                        .HasMaxLength(200);

                    b.Property<string>("Xpapel")
                        .IsRequired()
                        .HasColumnName("XPAPEL")
                        .HasMaxLength(200);

                    b.HasKey("PapelId");

                    b.ToTable("papel");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.ProcessoSeletivo", b =>
                {
                    b.Property<string>("ProcessoSeletivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PROCESSO_SELETIVO_ID")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Datahora")
                        .HasColumnName("DATAHORA")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsConcluido")
                        .HasColumnName("IS_CONCLUIDO")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("IsIniciado")
                        .HasColumnName("IS_INICIADO")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnName("PERIODO")
                        .HasMaxLength(6);

                    b.HasKey("ProcessoSeletivoId");

                    b.ToTable("processo_seletivo");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.ProcessoSeletivoCurso", b =>
                {
                    b.Property<string>("ProcessoSeletivoCursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PROCESSO_SELETIVO_CURSO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("CursoId")
                        .IsRequired()
                        .HasColumnName("CURSO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("ProcessoSeletivoId")
                        .IsRequired()
                        .HasColumnName("PROCESSO_SELETIVO_ID")
                        .HasMaxLength(200);

                    b.HasKey("ProcessoSeletivoCursoId");

                    b.HasIndex("CursoId")
                        .HasName("FK_PROCESSO_SELETIVO_CURSO_CURSO");

                    b.HasIndex("ProcessoSeletivoId")
                        .HasName("FK_PROCESSO_SELETIVO_CURSO_PROCESSO_SELETIVO");

                    b.ToTable("processo_seletivo_curso");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Prova", b =>
                {
                    b.Property<string>("ProvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PROVA_ID")
                        .HasMaxLength(200);

                    b.Property<DateTime>("DatahoraAplicacao")
                        .HasColumnName("DATAHORA_APLICACAO")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsBolsa")
                        .HasColumnName("IS_BOLSA")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("IsPratica")
                        .HasColumnName("IS_PRATICA")
                        .HasColumnType("bit(1)");

                    b.Property<bool>("IsTeoria")
                        .HasColumnName("IS_TEORIA")
                        .HasColumnType("bit(1)");

                    b.Property<string>("Sala")
                        .IsRequired()
                        .HasColumnName("SALA")
                        .HasMaxLength(200);

                    b.Property<string>("VagaRequisicaoId")
                        .IsRequired()
                        .HasColumnName("VAGA_REQUISICAO_ID")
                        .HasMaxLength(200);

                    b.HasKey("ProvaId");

                    b.HasIndex("VagaRequisicaoId")
                        .HasName("FK_PROVA_VAGA_REQUISICAO");

                    b.ToTable("prova");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USUARIO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnName("MATRICULA")
                        .HasMaxLength(200);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnName("SENHA")
                        .HasMaxLength(200);

                    b.Property<string>("Xusuario")
                        .IsRequired()
                        .HasColumnName("XUSUARIO")
                        .HasMaxLength(200);

                    b.HasKey("UsuarioId");

                    b.ToTable("usuario");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.UsuarioPapel", b =>
                {
                    b.Property<string>("UsuarioPapelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("USUARIO_PAPEL_ID")
                        .HasMaxLength(200);

                    b.Property<string>("CursoId")
                        .IsRequired()
                        .HasColumnName("CURSO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("PapelId")
                        .IsRequired()
                        .HasColumnName("PAPEL_ID")
                        .HasMaxLength(200);

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnName("USUARIO_ID")
                        .HasMaxLength(200);

                    b.HasKey("UsuarioPapelId");

                    b.HasIndex("CursoId")
                        .HasName("FK_USUARIO_PAPEL_CURSO");

                    b.HasIndex("PapelId")
                        .HasName("FK_USUARIO_PAPEL_PAPEL");

                    b.HasIndex("UsuarioId")
                        .HasName("FK_USUARIO_PAPEL_USUARIO");

                    b.ToTable("usuario_papel");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Vaga", b =>
                {
                    b.Property<string>("VagaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VAGA_ID")
                        .HasMaxLength(200);

                    b.Property<bool>("IsBolsa")
                        .HasColumnName("IS_BOLSA")
                        .HasColumnType("bit(1)");

                    b.Property<int>("NumeroVaga")
                        .HasColumnName("NUMERO_VAGA")
                        .HasColumnType("int(11)");

                    b.Property<string>("VagaRequisicaoId")
                        .IsRequired()
                        .HasColumnName("VAGA_REQUISICAO_ID")
                        .HasMaxLength(200);

                    b.HasKey("VagaId");

                    b.HasIndex("VagaRequisicaoId")
                        .HasName("FK_VAGA_VAGA_REQUISICAO");

                    b.ToTable("vaga");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.VagaRequisicao", b =>
                {
                    b.Property<string>("VagaRequisicaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VAGA_REQUISICAO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("ComponenteCurricularId")
                        .IsRequired()
                        .HasColumnName("COMPONENTE_CURRICULAR_ID")
                        .HasMaxLength(200);

                    b.Property<string>("ProcessoSeletivoCursoId")
                        .IsRequired()
                        .HasColumnName("PROCESSO_SELETIVO_CURSO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("ProfessorId")
                        .IsRequired()
                        .HasColumnName("PROFESSOR_ID")
                        .HasMaxLength(200);

                    b.Property<int>("Quantidade")
                        .HasColumnName("QUANTIDADE")
                        .HasColumnType("int(11)");

                    b.HasKey("VagaRequisicaoId");

                    b.HasIndex("ComponenteCurricularId")
                        .HasName("FK_VAGA_REQUISICAO_COMPONENTE_CURRICULAR");

                    b.HasIndex("ProcessoSeletivoCursoId")
                        .HasName("FK_VAGA_REQUISICAO_PROCESSO_SELETIVO_CURSO");

                    b.HasIndex("ProfessorId")
                        .HasName("FK_VAGA_REQUISICAO_PROFESSOR");

                    b.ToTable("vaga_requisicao");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.VagaRequisicaoAprovacao", b =>
                {
                    b.Property<string>("VagaRequisicaoId")
                        .HasColumnName("VAGA_REQUISICAO_ID")
                        .HasMaxLength(200);

                    b.Property<string>("CoordenadorId")
                        .IsRequired()
                        .HasColumnName("COORDENADOR_ID")
                        .HasMaxLength(200);

                    b.Property<bool>("IsAprovado")
                        .HasColumnName("IS_APROVADO")
                        .HasColumnType("bit(1)");

                    b.Property<int>("QuantidadeAprovada")
                        .HasColumnName("QUANTIDADE_APROVADA")
                        .HasColumnType("int(11)");

                    b.Property<int>("QuantidadeComBolsa")
                        .HasColumnName("QUANTIDADE_COM_BOLSA")
                        .HasColumnType("int(11)");

                    b.Property<int>("QuantidadeSemBolsa")
                        .HasColumnName("QUANTIDADE_SEM_BOLSA")
                        .HasColumnType("int(11)");

                    b.HasKey("VagaRequisicaoId");

                    b.HasIndex("CoordenadorId")
                        .HasName("FK_VAGA_REQUISICAO_APROVACAO_COORDENADOR");

                    b.ToTable("vaga_requisicao_aprovacao");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.ComponenteCurricular", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Curso", "Curso")
                        .WithMany("ComponenteCurricular")
                        .HasForeignKey("CursoId")
                        .HasConstraintName("FK_COMPONENTE_CURRICULAR_CURSO");

                    b.HasOne("GMonitoria.Domain.Entities.Usuario", "Professor")
                        .WithMany("ComponenteCurricular")
                        .HasForeignKey("ProfessorId")
                        .HasConstraintName("FK_COMPONENTE_CURRICULAR_PROFESSOR");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.HorarioAtendimento", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Inscricao", "Inscricao")
                        .WithMany("HorarioAtendimento")
                        .HasForeignKey("InscricaoId")
                        .HasConstraintName("FK_HORARIO_ATENDIMENTO_INSCRICAO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Inscricao", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Usuario", "Aluno")
                        .WithMany("Inscricao")
                        .HasForeignKey("AlunoId")
                        .HasConstraintName("FK_INSCRICAO_ALUNO");

                    b.HasOne("GMonitoria.Domain.Entities.VagaRequisicao", "VagaRequisicao")
                        .WithMany("Inscricao")
                        .HasForeignKey("VagaRequisicaoId")
                        .HasConstraintName("FK_INSCRICAO_VAGA_REQUISICAO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.InscricaoAceitacaoMonitoria", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Inscricao", "Inscricao")
                        .WithMany("InscricaoAceitacaoMonitoria")
                        .HasForeignKey("InscricaoId")
                        .HasConstraintName("FK_INSCRICAO_ACEITACAO_MONITORIA_INSCRICAO");

                    b.HasOne("GMonitoria.Domain.Entities.Vaga", "Vaga")
                        .WithMany("InscricaoAceitacaoMonitoria")
                        .HasForeignKey("VagaId")
                        .HasConstraintName("FK_INSCRICAO_ACEITACAO_MONITORIA_VAGA");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.InscricaoProva", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Inscricao", "Inscricao")
                        .WithMany("InscricaoProva")
                        .HasForeignKey("InscricaoId")
                        .HasConstraintName("FK_INSCRICAO_PROVA_INSCRICAO");

                    b.HasOne("GMonitoria.Domain.Entities.Prova", "Prova")
                        .WithMany("InscricaoProva")
                        .HasForeignKey("ProvaId")
                        .HasConstraintName("FK_INSCRICAO_PROVA_PROVA");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.InscricaoResultado", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Inscricao", "Inscricao")
                        .WithMany("InscricaoResultado")
                        .HasForeignKey("InscricaoId")
                        .HasConstraintName("FK_INSCRICAO_RESULTADO_INSCRICAO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.ProcessoSeletivoCurso", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Curso", "Curso")
                        .WithMany("ProcessoSeletivoCurso")
                        .HasForeignKey("CursoId")
                        .HasConstraintName("FK_PROCESSO_SELETIVO_CURSO_CURSO");

                    b.HasOne("GMonitoria.Domain.Entities.ProcessoSeletivo", "ProcessoSeletivo")
                        .WithMany("ProcessoSeletivoCurso")
                        .HasForeignKey("ProcessoSeletivoId")
                        .HasConstraintName("FK_PROCESSO_SELETIVO_CURSO_PROCESSO_SELETIVO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Prova", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.VagaRequisicao", "VagaRequisicao")
                        .WithMany("Prova")
                        .HasForeignKey("VagaRequisicaoId")
                        .HasConstraintName("FK_PROVA_VAGA_REQUISICAO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.UsuarioPapel", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Curso", "Curso")
                        .WithMany("UsuarioPapel")
                        .HasForeignKey("CursoId")
                        .HasConstraintName("FK_USUARIO_PAPEL_CURSO");

                    b.HasOne("GMonitoria.Domain.Entities.Papel", "Papel")
                        .WithMany("UsuarioPapel")
                        .HasForeignKey("PapelId")
                        .HasConstraintName("FK_USUARIO_PAPEL_PAPEL");

                    b.HasOne("GMonitoria.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPapel")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK_USUARIO_PAPEL_USUARIO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.Vaga", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.VagaRequisicao", "VagaRequisicao")
                        .WithMany("Vaga")
                        .HasForeignKey("VagaRequisicaoId")
                        .HasConstraintName("FK_VAGA_VAGA_REQUISICAO");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.VagaRequisicao", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.ComponenteCurricular", "ComponenteCurricular")
                        .WithMany("VagaRequisicao")
                        .HasForeignKey("ComponenteCurricularId")
                        .HasConstraintName("FK_VAGA_REQUISICAO_COMPONENTE_CURRICULAR");

                    b.HasOne("GMonitoria.Domain.Entities.ProcessoSeletivoCurso", "ProcessoSeletivoCurso")
                        .WithMany("VagaRequisicao")
                        .HasForeignKey("ProcessoSeletivoCursoId")
                        .HasConstraintName("FK_VAGA_REQUISICAO_PROCESSO_SELETIVO_CURSO");

                    b.HasOne("GMonitoria.Domain.Entities.Usuario", "Professor")
                        .WithMany("VagaRequisicao")
                        .HasForeignKey("ProfessorId")
                        .HasConstraintName("FK_VAGA_REQUISICAO_PROFESSOR");
                });

            modelBuilder.Entity("GMonitoria.Domain.Entities.VagaRequisicaoAprovacao", b =>
                {
                    b.HasOne("GMonitoria.Domain.Entities.Usuario", "Coordenador")
                        .WithMany("VagaRequisicaoAprovacao")
                        .HasForeignKey("CoordenadorId")
                        .HasConstraintName("FK_VAGA_REQUISICAO_APROVACAO_COORDENADOR");

                    b.HasOne("GMonitoria.Domain.Entities.VagaRequisicao", "VagaRequisicao")
                        .WithOne("VagaRequisicaoAprovacao")
                        .HasForeignKey("GMonitoria.Domain.Entities.VagaRequisicaoAprovacao", "VagaRequisicaoId")
                        .HasConstraintName("FK_VAGA_REQUISICAO_APROVACAO_VAGA_REQUISICAO");
                });
#pragma warning restore 612, 618
        }
    }
}
