
DROP TABLE HORARIO_ATENDIMENTO;
DROP TABLE INSCRICAO_ACEITACAO_MONITORIA;
DROP TABLE INSCRICAO_RESULTADO;
DROP TABLE INSCRICAO_PROVA;
DROP TABLE INSCRICAO;

DROP TABLE PROVA;
DROP TABLE VAGA;
DROP TABLE VAGA_REQUISICAO;   
DROP TABLE PROCESSO_SELETIVO_CURSO;
DROP TABLE PROCESSO_SELETIVO ;

DROP TABLE COMPONENTE_CURRICULAR;
DROP TABLE PROFESSOR;
DROP TABLE COORDENADOR;
DROP TABLE CURSO;
DROP TABLE ALUNO;




CREATE TABLE ALUNO(
	MATRICULA VARCHAR (200) NOT NULL,
	XALUNO VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CURSO PRIMARY KEY (MATRICULA)
);

CREATE TABLE CURSO(
	CURSO_ID VARCHAR (200) NOT NULL,
	XCURSO VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CURSO PRIMARY KEY (CURSO_ID )
);

CREATE TABLE PROFESSOR(
	PROFESSOR_ID VARCHAR (200) NOT NULL,
	XPROFESSOR VARCHAR(200) NOT NULL,
	CONSTRAINT PK_PROFESSOR PRIMARY KEY (PROFESSOR_ID )
);

CREATE TABLE COORDENADOR(
	COORDENADOR_ID VARCHAR (200) NOT NULL,
	XCOORDENADOR VARCHAR(200) NOT NULL,
    CURSO_ID VARCHAR(200) NOT NULL,
	CONSTRAINT PK_COORDENADOR PRIMARY KEY (COORDENADOR_ID ),
    CONSTRAINT FK_COORDENADOR_CURRICULAR_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSO (CURSO_ID)

);

CREATE TABLE COMPONENTE_CURRICULAR(
	COMPONENTE_CURRICULAR_ID VARCHAR (200) NOT NULL,
	XCOMPONENTE_CURRICULAR VARCHAR(200) NOT NULL,
    CURSO_ID VARCHAR (200) NOT NULL,
    PROFESSOR_ID VARCHAR(200) NOT NULL,
	CONSTRAINT PK_COMPONENTE_CURRICULAR PRIMARY KEY (COMPONENTE_CURRICULAR_ID),
	CONSTRAINT FK_COMPONENTE_CURRICULAR_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSO (CURSO_ID),
	CONSTRAINT FK_COMPONENTE_CURRICULAR_PROFESSOR FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR (PROFESSOR_ID)
);

CREATE TABLE PROCESSO_SELETIVO (
	PROCESSO_SELETIVO_ID VARCHAR(200) NOT NULL,
    PERIODO VARCHAR(6) NOT NULL,
    DATAHORA DATETIME NOT NULL,
    IS_INICIADO BIT NOT NULL,
    IS_CONCLUIDO BIT NULL,
    CONSTRAINT PK_PROCESSO_SELETIVO PRIMARY KEY (PROCESSO_SELETIVO_ID)
);

CREATE TABLE PROCESSO_SELETIVO_CURSO(
	PROCESSO_SELETIVO_CURSO_ID VARCHAR (200) NOT NULL,
	PROCESSO_SELETIVO_ID VARCHAR (200) NOT NULL,
    CURSO_ID VARCHAR (200) NOT NULL,
    VAGAR_REQUISICAO_ID VARCHAR (200) NOT NULL,
    CONSTRAINT PK_PROCESSO_SELETIVO_CURSO PRIMARY KEY (PROCESSO_SELETIVO_CURSO_ID),
    CONSTRAINT FK_PROCESSO_SELETIVO_CURSO_PROCESSO_SELETIVO FOREIGN KEY (PROCESSO_SELETIVO_ID) REFERENCES PROCESSO_SELETIVO (PROCESSO_SELETIVO_ID),
	CONSTRAINT FK_PROCESSO_SELETIVO_CURSO_CURSO FOREIGN KEY (CURSO_ID) REFERENCES CURSO (CURSO_ID)
);  

CREATE TABLE VAGA_REQUISICAO(
	VAGA_REQUISICAO_ID VARCHAR (200) NOT NULL,    
	PROCESSO_SELETIVO_CURSO_ID VARCHAR(200) NOT NULL,
	QUANTIDADE INT  NOT NULL,
	QUANTIDADE_ACEITA INT,
	QUANTIDADE_BOLSA INT ,
	COMPONENTE_CURRICULAR_ID VARCHAR(200) NOT NULL,
	ACEITACAO BIT NOT NULL,
	PROFESSOR_ID VARCHAR (200) NOT NULL,
	PROCESSO_SELETIVO_SELETIVO_CURSO_ID INT NOT NULL,
	CONSTRAINT PK_VAGA_REQUISICAO_ID PRIMARY KEY (VAGA_REQUISICAO_ID ),
	CONSTRAINT FK_VAGA_REQUISICAO_PROCESSO_SELETIVO_CURSO FOREIGN KEY (PROCESSO_SELETIVO_CURSO_ID) REFERENCES PROCESSO_SELETIVO_CURSO (PROCESSO_SELETIVO_CURSO_ID),
	CONSTRAINT FK_VAGA_REQUISICAO_PROFESSOR FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR (PROFESSOR_ID),
	CONSTRAINT FK_VAGA_REQUISICAO_COMPONENTE_CURRICULAR FOREIGN KEY (COMPONENTE_CURRICULAR_ID) REFERENCES COMPONENTE_CURRICULAR (COMPONENTE_CURRICULAR_ID)
 );
    
CREATE TABLE VAGA(
	VAGA_ID VARCHAR(200) NOT NULL,
	VAGA_REQUISICAO_ID VARCHAR (200) NOT NULL,
	IS_BOLSA BIT NOT NULL,
	NUMERO_VAGA INT NOT NULL,
	CONSTRAINT PK_VAGA PRIMARY KEY ( VAGA_ID ),
	CONSTRAINT FK_VAGA_VAGA_REQUISICAO FOREIGN KEY (VAGA_REQUISICAO_ID) REFERENCES VAGA_REQUISICAO (VAGA_REQUISICAO_ID)
);

CREATE TABLE PROVA(
	PROVA_ID VARCHAR(200) NOT NULL,
	VAGA_REQUISICAO_ID VARCHAR (200) NOT NULL,
    DATAHORA_APLICACAO DATETIME NOT NULL,
    SALA VARCHAR(200) NOT NULL,
    IS_TEORIA BIT NOT NULL,
    IS_PRATICA BIT NOT NULL, 
	IS_BOLSA BIT NOT NULL,
	CONSTRAINT PK_PROVA PRIMARY KEY ( PROVA_ID),
	CONSTRAINT FK_PROVA_VAGA_REQUISICAO  FOREIGN KEY (VAGA_REQUISICAO_ID) REFERENCES VAGA_REQUISICAO (VAGA_REQUISICAO_ID)
);
 
CREATE TABLE INSCRICAO(
    INSCRICAO_ID VARCHAR (200) NOT NULL,
    MATRICULA VARCHAR (200) NOT NULL,
    CPF VARCHAR (200) NOT NULL,
    PROTOCOLO VARCHAR (200) NOT NULL,
    VAGA_REQUISICAO_ID VARCHAR  (200) NOT NULL,
    CONSTRAINT PK_INSCRICAO PRIMARY KEY (INSCRICAO_ID ),
    CONSTRAINT FK_INSCRICAO_ALUNO FOREIGN KEY (MATRICULA) REFERENCES ALUNO (MATRICULA),
    CONSTRAINT FK_INSCRICAO_VAGA_REQUISICAO FOREIGN KEY (VAGA_REQUISICAO_ID) REFERENCES VAGA_REQUISICAO (VAGA_REQUISICAO_ID)
);
    
CREATE TABLE INSCRICAO_RESULTADO(
	INSCRICAO_RESULTADO_ID VARCHAR (200) NOT NULL,
	CLASSIFICACAO INT,
	INSCRICAO_ID VARCHAR (200) NOT NULL,
    CONSTRAINT PK_INSCRICAO_RESULTADO PRIMARY KEY (INSCRICAO_RESULTADO_ID ),
    CONSTRAINT FK_INSCRICAO_RESULTADO_INSCRICAO FOREIGN KEY (INSCRICAO_ID) REFERENCES INSCRICAO (INSCRICAO_ID)
);
    
    
CREATE TABLE INSCRICAO_ACEITACAO_MONITORIA(
    INSCRICAO_ACEITACAO_MONITORIA_ID VARCHAR (200) NOT NULL,
    INSCRICAO_ID VARCHAR(200) NOT NULL,
    VAGA_ID VARCHAR (200) NOT NULL,
    CONSTRAINT PK_INSCRICAO_ACEITACAO_MONITORIA PRIMARY KEY (INSCRICAO_ACEITACAO_MONITORIA_ID),
    CONSTRAINT FK_INSCRICAO_ACEITACAO_MONITORIA_INSCRICAO FOREIGN KEY (INSCRICAO_ID) REFERENCES INSCRICAO (INSCRICAO_ID),
    CONSTRAINT FK_INSCRICAO_ACEITACAO_MONITORIA_VAGA FOREIGN KEY (VAGA_ID) REFERENCES VAGA (VAGA_ID)
);
    
CREATE  TABLE INSCRICAO_PROVA (
	INSCRICAO_PROVA_ID VARCHAR (200) NOT NULL,
    NOTA FLOAT NOT NULL,
    PROVA_ID VARCHAR (200) NOT NULL,
    INSCRICAO_ID VARCHAR (200) NOT NULL,
    CONSTRAINT PK_INSCRICAO_PROVA PRIMARY KEY (INSCRICAO_PROVA_ID),
    CONSTRAINT FK_INSCRICAO_PROVA_INSCRICAO FOREIGN KEY (INSCRICAO_ID) REFERENCES INSCRICAO (INSCRICAO_ID),
    CONSTRAINT FK_INSCRICAO_PROVA_PROVA FOREIGN KEY (PROVA_ID) REFERENCES PROVA (PROVA_ID)
);
     
CREATE TABLE HORARIO_ATENDIMENTO(
    HORARIO_ATENDIMENTO_ID VARCHAR (200) NOT NULL,
    INSCRICAO_ID VARCHAR (200) NOT NULL,
    DIA_DA_SEMANA VARCHAR (200) NOT NULL,
    HORA_INICIO DATETIME NOT NULL,
    HORA_FIM DATETIME NOT NULL,
    MES INT NOT NULL,
    SALA VARCHAR (200) NOT NULL,
    CONSTRAINT PK_HORARIO_ATENDIMENTO PRIMARY KEY (HORARIO_ATENDIMENTO_ID),
    CONSTRAINT FK_HORARIO_ATENDIMENTO_INSCRICAO FOREIGN KEY (INSCRICAO_ID) REFERENCES INSCRICAO (INSCRICAO_ID)
 );
    
      